#!/bin/bash
# Fabric Server Installation Script
# Verifies Java installation and sets up server environment for Pterodactyl

set -e

echo "=========================================="
echo "Fabric Server Installation Script"
echo "=========================================="

# Verify Java installation (Zulu 21)
echo ""
echo "Verifying Java installation..."
if ! command -v java &> /dev/null; then
    echo "ERROR: Java is not installed or not in PATH"
    echo "Please ensure Java 21+ is installed"
    exit 1
fi

# Check Java version
echo "Java version:"
java -version

# Verify it's Java 21 or higher
JAVA_VERSION=$(java -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f1)
if [ "$JAVA_VERSION" -lt 21 ]; then
    echo "WARNING: Java version is less than 21. Recommended: Java 21+"
    echo "Current version: $JAVA_VERSION"
else
    echo "✓ Java 21+ detected"
fi

# Check for server.jar (use environment variable if set, otherwise default)
SERVER_JAR="${SERVER_JARFILE:-server.jar}"
if [ ! -f "$SERVER_JAR" ]; then
    echo ""
    echo "WARNING: $SERVER_JAR not found in current directory"
    echo "Expected location: $(pwd)/$SERVER_JAR"
    echo "Please upload your server JAR file before starting the server"
else
    echo "✓ Server JAR found: $SERVER_JAR"
fi

# Create necessary directories
echo ""
echo "Creating server directories..."
mkdir -p world logs mods config
mkdir -p kubejs/server_scripts kubejs/startup_scripts 2>/dev/null || true
mkdir -p patchouli_books 2>/dev/null || true

echo "✓ Directories created"

# Set up EULA if not present
if [ ! -f "eula.txt" ]; then
    echo ""
    echo "Creating eula.txt..."
    echo "eula=true" > eula.txt
    echo "✓ EULA accepted"
else
    echo "✓ EULA already exists"
fi

# Create initial server.properties if not present
if [ ! -f "server.properties" ]; then
    echo ""
    echo "Creating default server.properties..."
    cat > server.properties << 'EOF'
#Minecraft server properties
#Generated by Fabric Server installation script

motd=A Minecraft Server
server-port=25565
max-players=20
online-mode=true
white-list=false
pvp=true
difficulty=easy
hardcore=false
view-distance=10
simulation-distance=10
spawn-protection=16
max-tick-time=60000
enable-command-block=false
enable-query=false
enable-rcon=false
resource-pack=
resource-pack-prompt=
sync-chunk-writes=true
use-native-transport=true
enable-jmx-monitoring=false
enable-status=true
enforce-whitelist=false
function-permission-level=2
op-permission-level=4
EOF
    echo "✓ Default server.properties created"
else
    echo "✓ server.properties already exists"
fi

# Set proper permissions
echo ""
echo "Setting file permissions..."
chmod 755 . 2>/dev/null || true
chmod 644 eula.txt server.properties 2>/dev/null || true
find . -type d -exec chmod 755 {} \; 2>/dev/null || true
find . -type f -exec chmod 644 {} \; 2>/dev/null || true
if [ -f "$SERVER_JAR" ]; then
    chmod +x "$SERVER_JAR" 2>/dev/null || true
fi

echo "✓ Permissions set"

# Verify installation
echo ""
echo "=========================================="
echo "Installation Summary"
echo "=========================================="
echo "Server JAR: $SERVER_JAR"
echo "Java: $(which java)"
echo "Java Version: $(java -version 2>&1 | head -n 1)"
echo "Working Directory: $(pwd)"
echo ""
echo "Installation complete!"
echo "You can now start your Fabric server."

